# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 15:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestana', models.CharField(choices=[(b'S', b'SOMOS'), (b'SE', b'SERVICIOS'), (b'E', b'EQUIPO'), (b'T', b'TESTIMONIOS'), (b'C', 'CONT\xc1CTANOS')], default=b'S', max_length=30, verbose_name=b'Pesta\xc3\xb1a')),
                ('titulo', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo')),
                ('texto', ckeditor.fields.RichTextField(verbose_name=b'Texto')),
                ('imagen', filebrowser.fields.FileBrowseField(help_text=b'Tama\xc3\xb1o Recomendado: 1919X279', max_length=200, verbose_name=b'Imagen:')),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha')),
                ('tipo', models.CharField(max_length=120, verbose_name=b'Tipo de cliente')),
                ('nombre', models.CharField(max_length=120, verbose_name=b'Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('telefono', models.CharField(max_length=80, verbose_name=b'Telefono')),
                ('mensaje', models.TextField(verbose_name=b'Mensaje')),
            ],
            options={
                'ordering': ['-fecha'],
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_diferencial', ckeditor.fields.RichTextField(verbose_name=b'Texto')),
                ('imagen_diferencial', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'Imagen')),
                ('fondo_diferencial', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'Fondo')),
                ('imagen_equipo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'Imagen de equipo')),
                ('imagen_video', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'Imagen Video')),
                ('video_enlace', models.URLField(blank=True, verbose_name=b'URL del Video')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name=b'Posici\xc3\xb3n')),
                ('titulo', models.CharField(max_length=100, verbose_name=b'Titulo:')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name=b'Subt\xc3\xadtulo')),
                ('texto_1', models.CharField(blank=True, max_length=100, verbose_name=b'Texto 1')),
                ('texto_2', models.CharField(blank=True, max_length=100, verbose_name=b'Texto 2')),
                ('conocenos_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Texto de bot\xc3\xb3n')),
                ('enlace_boton', models.URLField(blank=True, verbose_name=b'Enlace del bot\xc3\xb3n')),
                ('fondo', filebrowser.fields.FileBrowseField(blank=True, help_text=b'Tama\xc3\xb1o Recomendado: 1920x400', max_length=200, verbose_name=b'Fondo:')),
                ('pdf', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'PDF')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_home', to='web.Home')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Banner de Home',
                'verbose_name_plural': 'Banners de Home',
            },
        ),
        migrations.CreateModel(
            name='InfoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name=b'Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name=b'Creado por')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name=b'Modificado por')),
                ('direccion', models.CharField(help_text=b'Agregar // para generar el salto de l\xc3\xadnea', max_length=120, verbose_name=b'Direcci\xc3\xb3n')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('telefono', models.CharField(max_length=60, verbose_name=b'Tel\xc3\xa9fono')),
                ('email_form', models.EmailField(blank=True, max_length=254, verbose_name=b'Formulario de Contacto')),
                ('site', models.CharField(blank=True, help_text=b'Ingrese la url actual del sitio sin el slash final', max_length=60, verbose_name=b'URL del sitio')),
                ('facebook', models.URLField(blank=True, verbose_name=b'Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name=b'Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name=b'Linkedin')),
                ('skype', models.CharField(blank=True, max_length=160, verbose_name=b'Skype')),
                ('intranet', models.URLField(blank=True, verbose_name=b'Intranet')),
                ('ga', models.CharField(blank=True, help_text=b'Opcional: Inserte el c\xc3\xb3digo que google analitycs le\n       proporciona con el formato: UA-XXXXX-X', max_length=24, verbose_name=b'Google Analytics')),
                ('coordenadas', geoposition.fields.GeopositionField(max_length=42)),
                ('paquetes', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'PDF de paquetes')),
                ('foto_contactanos', filebrowser.fields.FileBrowseField(blank=True, help_text='Tama\xf1o recomendado:366x210', max_length=200, verbose_name=b'Foto de cont\xc3\xa1ctanos')),
            ],
            options={
                'verbose_name_plural': 'Informaci\xf3n del Sitio',
            },
        ),
    ]
