# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-26 16:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_example', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name=b'Imagen Label')),
                ('rich_example', ckeditor.fields.RichTextField(blank=True, verbose_name=b'Example')),
            ],
            options={
                'verbose_name': 'Model Exmaple',
                'verbose_name_plural': 'Model Examples',
            },
        ),
    ]
